version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTgRES_USER: postgres
      POSTgRES_PASSWORD: postgres
      POSTgRES_DB: xipsoft_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
